server:
  port: 8082
mybatis:
  mapper-locations: # 所有的mapper映射文件
    - classpath:mapping/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/springcloud3?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: root # 数据库连接密码
  application:
    name: microCould-product
#  security:
#    user:
#      name: admin
#      password: enjoy
#      roles:
#        -USER
logging:
  level:
    cn.enjoy.mapper: debug
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone:  http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance:
    instance-id: microCould-product3
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 #没置心·弥的时行问隔（默认是30{秒)
    lease-expiration-duration-in-seconds: 5 #如i果现在超过了5秒的问隔(默认是90秒)

info:
  app.name: microCould-product
  company.name: enjoy
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$