server:
  port: 9501

eureka:
  client:
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
    instance:
      instance-id: microcloud-zuul-gateway
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
      lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）

spring:
  application:
    name:  microcloud-zuul-gateway

zuul:
  routes:
#    microcloud-provider-users: /user-poxy/**
    user:
      path: /user-proxy/**
      serviceId: microcloud-provider-users
    user2:
      path: /user-proxy2/**
      url: http://localhost:8090
    product:
      path: /product-proxy/**
      serviceId: micro-could-product
  ignored-services:
#    microcloud-provider-users
    "*"
  prefix: /enjoy-api